output "cloudfront_url" {
  description = "Public HTTPS URL of the static frontend (generated CloudFront domain). FR-011, AC-011."
  value       = "https://${aws_cloudfront_distribution.frontend.domain_name}"
}

output "cloudfront_distribution_id" {
  description = "CloudFront distribution ID (for cache invalidation / cleanup)."
  value       = aws_cloudfront_distribution.frontend.id
}

output "api_base_url" {
  description = "API Gateway default execute-api base URL. Non-secret; consumed by frontend config."
  value       = aws_apigatewayv2_api.http.api_endpoint
}

output "frontend_bucket_name" {
  description = "Private S3 bucket holding the frontend assets."
  value       = aws_s3_bucket.frontend.id
}

output "dynamodb_table_name" {
  description = "Feedback DynamoDB table name."
  value       = aws_dynamodb_table.feedback.name
}

output "lambda_function_name" {
  description = "Backend Lambda function name."
  value       = aws_lambda_function.api.function_name
}

output "lambda_log_group" {
  description = "CloudWatch log group for the backend Lambda."
  value       = aws_cloudwatch_log_group.lambda.name
}

output "organizer_key_is_generated" {
  description = "True when no organizer_key was supplied and one was generated by Terraform."
  value       = nonsensitive(var.organizer_key == "")
}

output "organizer_key" {
  description = "Effective organizer access key (sensitive). Retrieve via `terraform output -raw organizer_key`."
  value       = local.organizer_key
  sensitive   = true
}
